### PR TITLE
Fix typo: color->transparency

### PR DESCRIPTION
**Pull request by mgrudzinska**

### CODE REVIEW

**Review by mbasaglia — APPROVED** [review]

**Comment by mbasaglia** [comment]
Small fix, so it only needs 1 approval. merging

**Comment by mbasaglia** [comment]
Actually, before I merge, @mgrudzinska you should sign the agreement: https://github.com/lottie/lottie-spec/blob/main/Notices.md

@fmalita I think you set up the cla-bot initally, it seems to no longer be working :thinking:

**Comment by mbasaglia** [comment]
@cla-bot check

**Comment by mbasaglia** [comment]
Fixed it, I think

**Comment by mgrudzinska** [comment]
@mbasaglia https://github.com/lottie/lottie-spec/pull/108

**Review by b-wils — APPROVED** [review]

**Comment by mbasaglia** [comment]
@cla-bot check

**Pull request merged**
